export const content = {
  homepage: {
    id: 2,
    attributes: {
      description:
        "Built form scrat the admin website to manage activities on ubona wesite.",
      createdAt: "2022-01-30T21:36:02.561Z",
      updatedAt: "2022-01-30T21:36:04.129Z",
      publishedAt: "2022-01-30T21:36:04.127Z",
      workImage: null,
      data: {
        hero: {
          heroTitle: "Gestión y Eficiencia",
          heroSubtitle: "simple",
          heroDescription:
            "En nuestras manos depositás la tranquilidad de saber que  cumplimos con tus requerimientos.",
          coverTitle: "coverTitle",
          coverImage:
            "https://res.cloudinary.com/fletech/image/upload/v1655946024/small_hero_bcg_4d95185880.png",
        },
        banner: {
          title: "Qué hacemos?",
          description:
            "Recibimos tu consulta, analizamos el contexto y te ofrecemos el asesoramiento que mejor se adapta a tu solicitud, ya que contamos con una amplia gama de servicios propios, y otros servicios de profesionales aliados, para brindarte un servicio integral. ENCONTRÁ EL TUYO.",
        },
      },
    },
  },
  services: {
    data: [
      {
        id: 1,
        attributes: {
          title: "Gestoria del automotor",
          createdAt: "2022-06-08T15:44:23.388Z",
          updatedAt: "2022-06-08T15:45:18.477Z",
          publishedAt: "2022-06-08T15:45:18.475Z",
          type: "service",
          slug: "gestoria-del-automotor",
          description: null,
          services_offered: null,
          services_title: null,
          active: null,
          website: null,
          email: null,
          phone: null,
          address: null,
          contact_name: null,
          rol: null,
          company_name: null,
        },
      },
      {
        id: 2,
        attributes: {
          title: "Trámites generales",
          createdAt: "2022-06-08T15:45:06.920Z",
          updatedAt: "2022-07-17T17:35:34.952Z",
          publishedAt: "2022-06-08T15:45:29.618Z",
          type: "service",
          slug: "tramites-generales",
          description: null,
          services_offered: null,
          services_title: null,
          active: null,
          website: null,
          email: null,
          phone: null,
          address: null,
          contact_name: null,
          rol: null,
          company_name: null,
        },
      },
      {
        id: 3,
        attributes: {
          title: "Seguros generales",
          createdAt: "2022-06-08T15:46:35.347Z",
          updatedAt: "2022-06-08T15:46:36.671Z",
          publishedAt: "2022-06-08T15:46:36.670Z",
          type: "service",
          slug: "seguros-generales",
          description: null,
          services_offered: null,
          services_title: null,
          active: null,
          website: null,
          email: null,
          phone: null,
          address: null,
          contact_name: null,
          rol: null,
          company_name: null,
        },
      },
      {
        id: 4,
        attributes: {
          title: "Legales",
          createdAt: "2022-06-13T10:27:53.683Z",
          updatedAt: "2022-06-13T10:27:56.010Z",
          publishedAt: "2022-06-13T10:27:56.006Z",
          type: "alliance",
          slug: "legales",
          description: null,
          services_offered: null,
          services_title: null,
          active: null,
          website: null,
          email: null,
          phone: null,
          address: null,
          contact_name: null,
          rol: null,
          company_name: null,
        },
      },
      {
        id: 5,
        attributes: {
          title: "Contables",
          createdAt: "2022-06-13T10:29:37.391Z",
          updatedAt: "2022-06-13T10:29:38.351Z",
          publishedAt: "2022-06-13T10:29:38.349Z",
          type: "alliance",
          slug: "contables",
          description: null,
          services_offered: null,
          services_title: null,
          active: null,
          website: null,
          email: null,
          phone: null,
          address: null,
          contact_name: null,
          rol: null,
          company_name: null,
        },
      },
      {
        id: 6,
        attributes: {
          title: "Servicios inmobiliarios",
          createdAt: "2022-06-13T11:15:01.610Z",
          updatedAt: "2022-06-13T11:15:04.120Z",
          publishedAt: "2022-06-13T11:15:04.119Z",
          type: "alliance",
          slug: "servicios-inmobiliarios",
          description: null,
          services_offered: null,
          services_title: null,
          active: null,
          website: null,
          email: null,
          phone: null,
          address: null,
          contact_name: null,
          rol: null,
          company_name: null,
        },
      },
    ],
  },
  meta: {
    pagination: {
      page: 1,
      pageSize: 25,
      pageCount: 1,
      total: 2,
    },
  },
};
